version: '3.8'

services:
  web:
    # replace username/repo:tag with your name and image details
    image: aoleony2/urlshortner:v1
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.id
    ports:
      - "4000:80"
      - "8000:8000"
    volumes:
      - "/home/student/csc409_a2/a2group45/volumes/logs:/app/logs"
    networks:
      - webnet
    entrypoint: "gunicorn --workers=1 --threads=4 --log-file=logs/test.log --bind=0.0.0.0:8000 wsgi"
  redis-primary:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/student/csc409_a2/a2group45/volumes/redis/data:/data"
      - "/home/student/csc409_a2/a2group45/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
       constraints: [node.role == manager]
    command: redis-server
    networks:
      - webnet
  redis-replica-1:
    image: redis:latest
    depends_on:
      - redis-primary
    volumes:
      - "/home/student/csc409_a2/a2group45/volumes/redis/data:/data"
      - "/home/student/csc409_a2/a2group45/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: redis-server --replicaof redis-primary 6379
    networks:
      - webnet
  redis-replica-2:
    image: redis:latest
    depends_on:
      - redis-primary
    volumes:
      - "/home/student/csc409_a2/a2group45/volumes/redis/data:/data"
      - "/home/student/csc409_a2/a2group45/redis.conf:/usr/local/etc/redis/redis.conf"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: redis-server --replicaof redis-primary 6379
    networks:
      - webnet
  monitor_status:
    image: aoleony2/monitor:v1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "5000:80"
    volumes:
      - "/home/student/csc409_a2/a2group45/exp:/usr/bin/exp"
    networks:
      - webnet
networks:
  webnet: